// examples/taro/vue-2/src/pages/index/index.vue
<template>
  <view class="index bg-[#b5b5b5] h-screen pl-7.5" :class="{'text-[50px]': true}">
    <text :class="['font-bold', 'text-[#ffffff]']">{{ msg }}</text>
  </view>
</template>

<script>
import './index.css'

export default {
  data () {
    return {
      msg: 'Hello world!'
    }
  }
}
</script>

// examples/taro/react/src/pages/index/index.tsx
import { Component } from 'react'
import { View, Text } from '@tarojs/components'
import './index.css'

export default class Index extends Component {

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className={`index bg-[#b5b5b5] h-screen pl-7.5 ${true ? 'text-[50px]' : ''}`}>
        <Text className={`${'none'} font-bold text-[#ffffff]`}>Hello world!</Text>
      </View>
    )
  }
}
