// examples/uni-app/vue-3/src/pages/index/index.vue
<template>
	<view class="index bg-[#b5b5b5] h-screen pl-7.5" :class="{'text-[50px]': true}">
        <text :class="['font-bold', 'text-[#ffffff]']">{{ title }}</text>
    </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
const title = ref('Hello world!')
</script>

<style>
    .index {
        @apply pt-[45vh];
    }
</style>

// examples/taro/react/src/pages/index/index.tsx
import { Component } from 'react'
import { View, Text } from '@tarojs/components'
import './index.css'

export default class Index extends Component {

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className={`index bg-[#b5b5b5] h-screen pl-7.5 ${true ? 'text-[50px]' : ''}`}>
        <Text className={`${'none'} font-bold text-[#ffffff]`}>Hello world!</Text>
      </View>
    )
  }
}
